/**
 * @module Absorb
 *
 */
/**
 * Versions-only GitHub Actions updater for the repository the command is run
 * from. Two-phase pipeline (mirrors `Update.sh` → `Maintain Workflow`):
 *
 * Phase 1 - no absorb-marked `Update.sh` in the repository root: writes a
 * scoped `Update.sh` that pins every `uses:` reference inside `.github/` to
 * the latest tag and commit SHA, leaving every other byte of every file
 * intact. Run it, then re-run `Maintain Workflow --Absorb`.
 *
 * Phase 2 - absorb-marked `Update.sh` present: iterates over the Maintain
 * library's `Workflow/` templates (the canonical source of truth) and applies
 * the pinned template versions to the repository's workflow files. Only the
 * `uses:` version segment is replaced, and it is never downgraded; everything
 * else in the repository is left untouched.
 *
 */
export default async () => {
	const { cwd } = await import("node:process");

	const { readdir, readFile, writeFile, mkdir, access } =
		await import("node:fs/promises");

	const { join, resolve, dirname } = await import("node:path");

	const { fileURLToPath } = await import("node:url");

	const Root = resolve(dirname(fileURLToPath(import.meta.url)), "../../");

	const Cwd = cwd();

	const GitHub = join(Cwd, ".github");

	const Workflows = join(GitHub, "workflows");

	const Update = join(Cwd, "Update.sh");

	const TemplateDirectory = join(Root, "Workflow");

	const Mark = "# Generated by Maintain Workflow --Absorb";

	const Action = /uses:\s*([^\s"']+)/;

	const Yaml = async (Directory: string): Promise<string[]> => {
		try {
			const Entries = await readdir(Directory, { withFileTypes: true });

			return Entries.filter(
				(Entry) => Entry.isFile() && /\.ya?ml$/i.test(Entry.name),
			).map((Entry) => join(Directory, Entry.name));
		} catch {
			return [];
		}
	};

	const Exists = async (Path: string): Promise<boolean> => {
		try {
			await access(Path);

			return true;
		} catch {
			return false;
		}
	};

	// Ensure the canonical template directory exists (phase 2 iterates it).
	await mkdir(TemplateDirectory, { recursive: true });

	const Files = [...(await Yaml(GitHub)), ...(await Yaml(Workflows))];

	if (Files.length === 0) {
		console.log(
			`[Absorb] No YAML files found under ${GitHub} - nothing to absorb.`,
		);

		return;
	}

	const Actions = new Set<string>();

	for (const File of Files) {
		const Content = await readFile(File, "utf-8");

		for (const Line of Content.split("\n")) {
			const Match = Line.match(Action);

			if (Match === null) continue;

			const Value = (Match[1] ?? "").replace(/^["']|["']$/g, "");

			const Name = Value.split("@")[0] ?? "";

			if (Name.startsWith(".") || !Name.includes("/")) continue;

			Actions.add(Name);
		}
	}

	if (
		(await Exists(Update)) &&
		!(await readFile(Update, "utf-8")).includes(Mark)
	) {
		console.log(
			`[Absorb] ${Update} exists but is not marked as absorb-generated - refusing to overwrite it.`,
		);

		return;
	}

	if (await Exists(Update)) {
		await PhaseTwo();

		return;
	}

	await PhaseOne();

	/**
	 * Phase 1: write a scoped Update.sh into the repository root.
	 */
	async function PhaseOne() {
		const Source = await readFile(join(Root, "Update.sh"), "utf-8");

		const ManifestBlock = `\n${Mark}\n# Actions discovered in ${Cwd} at absorb time (informational).\nDiscoveredActions=( ${[...Actions].map((Name) => `"${Name}"`).join(" ")} )\n`;

		const Footer = `\nprint_status "Absorb verification"\nFAILED=0\nfor Action in "\${DiscoveredActions[@]}"; do\n\tif \\grep -rq "uses:[[:space:]]*\${Action}@" .github; then\n\t\tprint_success "\\u2192 \${Action} referenced in .github/"\n\telse\n\t\tprint_error "\\u2192 \${Action} not referenced in .github/"\n\t\tFAILED=$((FAILED+1))\n\tfi\ndone\n[ "\$FAILED" -eq 0 ] && print_success "Absorb Update.sh complete" || print_error "Absorb Update.sh finished with \${FAILED} unverified action(s)"\n`;

		// Scope the canonical pinner to `.github/` only: same pinning logic
		// (latest semver tag, annotated-tag deref, `@sha # tag`), zero risk to
		// anything outside the repository's GitHub configuration.
		const Scoped = Source.replace(
			/\\find \.[\s\S]*?-print0/,
			'\\find .github -type f \\( -iname "*.yml" -o -iname "*.yaml" \\) -print0',
		)
			.replace(
				'print_status "Starting Update.sh script"',
				`${ManifestBlock}print_status "Starting Update.sh script"`,
			)
			.replace(
				'print_status "Update complete"',
				`${Footer}print_status "Update complete"`,
			);

		await writeFile(Update, Scoped, { mode: 0o755 });

		console.log(`[Absorb] Phase 1 complete:`);
		console.log(`[Absorb]   Wrote: ${Update}`);
		console.log(`[Absorb]   Run:   bash ${Update}`);
		console.log(`[Absorb]   Then:  Maintain Workflow --Absorb`);
	}

	/**
	 * Phase 2: apply the canonical template versions to the repository's
	 * workflow files, in place, versions only.
	 */
	async function PhaseTwo() {
		const Pins = new Map<
			string,
			{ Ref: string; Tag: string | undefined }
		>();

		for (const File of await Yaml(TemplateDirectory)) {
			const Content = await readFile(File, "utf-8");

			for (const Line of Content.split("\n")) {
				const Match = Line.match(Action);

				if (Match === null) continue;

				const Value = (Match[1] ?? "").replace(/^["']|["']$/g, "");

				const [Name, Ref] = Value.split("@");

				if (
					Name === undefined ||
					Ref === undefined ||
					Name.startsWith(".") ||
					!Name.includes("/") ||
					Pins.has(Name)
				) {
					continue;
				}

				const Tag = /#\s*([^\s]+)/.exec(Line)?.[1];

				Pins.set(Name, { Ref, Tag });
			}
		}

		const Compare = (A: string, B: string): number => {
			const Left = A.replace(/^v/, "").split(".").map(Number);

			const Right = B.replace(/^v/, "").split(".").map(Number);

			for (
				let Index = 0;
				Index < Math.max(Left.length, Right.length);
				Index += 1
			) {
				const X = Left[Index] ?? 0;

				const Y = Right[Index] ?? 0;

				if (X !== Y) return X > Y ? 1 : -1;
			}

			return 0;
		};

		let Updated = 0;

		let Kept = 0;

		let Skipped = 0;

		for (const File of Files) {
			const Content = await readFile(File, "utf-8");

			const Next = Content.split("\n")
				.map((Line) => {
					const Match = Line.match(Action);

					if (Match === null) return Line;

					const Value = (Match[1] ?? "").replace(/^["']|["']$/g, "");

					const [Name, Ref] = Value.split("@");

					if (
						Name === undefined ||
						Ref === undefined ||
						Name.startsWith(".") ||
						!Name.includes("/")
					) {
						return Line;
					}

					const Pin = Pins.get(Name);

					if (Pin === undefined) {
						Skipped += 1;

						return Line;
					}

					const Tag = /#\s*([^\s]+)/.exec(Line)?.[1];

					if (
						Tag !== undefined &&
						Pin.Tag !== undefined &&
						Compare(Tag, Pin.Tag) > 0
					) {
						Kept += 1;

						return Line;
					}

					const Index = Match.index ?? 0;

					const Rest = Line.slice(Index + (Match[0]?.length ?? 0))
						.replace(/^\s*#.*$/, "")
						.replace(/\s+$/, "");

					Updated += 1;

					return `${Line.slice(0, Index)}uses: ${Name}@${Pin.Ref}${
						Pin.Tag === undefined ? "" : ` # ${Pin.Tag}`
					}${Rest.length > 0 ? ` ${Rest}` : ""}`;
				})
				.join("\n");

			if (Next !== Content) {
				await writeFile(File, Next);
			}
		}

		console.log(`[Absorb] Phase 2 complete:`);
		console.log(`[Absorb]   Template source: ${TemplateDirectory}`);
		console.log(`[Absorb]   Actions covered by templates: ${Pins.size}`);
		console.log(
			`[Absorb]   Updated: ${Updated}, kept (template older): ${Kept}, no template: ${Skipped}`,
		);
		console.log(
			`[Absorb]   ${Update} left in place - delete it to re-run phase 1.`,
		);
	}
};
