export default {
    color: true,
    format: "esm",
    logLevel: "debug",
    metafile: true,
    minify: true,
    outdir: "Target",
    platform: "node",
    target: "esnext",
    tsconfig: "tsconfig.json",
    write: true,
    legalComments: "none",
    bundle: false,
    assetNames: "Asset/[name]-[hash]",
    sourcemap: false,
    drop: ["debugger"],
    ignoreAnnotations: true,
    keepNames: false,
    plugins: [],
    define: {
        "process.env.VERSION_CLOUDFLARE_WRANGLER_ACTION": JSON.stringify(process.env["VERSION_CLOUDFLARE_WRANGLER_ACTION"]),
        "process.env.VERSION_ACTIONS_SETUP_NODE": JSON.stringify(process.env["VERSION_ACTIONS_SETUP_NODE"]),
        "process.env.VERSION_ACTIONS_UPLOAD_ARTIFACT": JSON.stringify(process.env["VERSION_ACTIONS_UPLOAD_ARTIFACT"]),
        "process.env.VERSION_ACTIONS_CACHE": JSON.stringify(process.env["VERSION_ACTIONS_CACHE"]),
        "process.env.VERSION_ACTIONS_RS_CARGO": JSON.stringify(process.env["VERSION_ACTIONS_RS_CARGO"]),
    },
};
